# Generated by Django 4.2.6 on 2024-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField()),
                ('course', models.CharField(choices=[('Html', 'html'), ('Css', 'css'), ('Javascript', 'javascript'), ('Python', 'python'), ('Cisco', 'cisco')], default='Html', max_length=25)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
